spring:
  config:
    activate:
      on-profile: prod

  datasource:
    hikari:
      jdbc-url: ${budget.guardian.spring.datasource.url}
      username: ${budget.guardian.spring.datasource.username}
      password: ${budget.guardian.spring.datasource.password}

  security:
    jwt:
      header: ${budget.guardian.spring.security.jwt.header}
      sign-key: ${budget.guardian.spring.security.jwt.sign-key}
      access-token-validity-in-seconds: ${budget.guardian.spring.security.jwt.access-token-validity-in-seconds}
      refresh-token-validity-in-seconds: ${budget.guardian.spring.security.jwt.refresh-token-validity-in-seconds}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${budget.guardian.spring.data.redis.host}
      port: ${budget.guardian.spring.data.redis.port}
      database: ${budget.guardian.spring.data.redis.database}

budget-guardian:
  host: ${budget.guardian.host}

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"